---
image:
  name: ghcr.io/oldtyt/hugo-docker
  entrypoint: [""]

variables:
  PUBLIC_URL: /

stages:
  - deploy

prod:
  stage: "deploy"
  script: [/entrypoint.sh]
  environment:
    name: production
    url: "https://devboxops.xyz"
  artifacts:
    paths:
    - public
  only:
    - main

devel:
  except: [main]
  artifacts:
    paths:
    - public
  environment:
    name: devel
    url: "https://dev.devboxops.xyz"
  script: [/entrypoint.sh]
  stage: deploy
  variables:
    BASE_URL: "https://dev.devboxops.xyz"
