---
image:
  name: ghcr.io/oldtyt/hugo-docker
  entrypoint: [""]

stages:
  - deploy

prod:
  stage: "deploy"
  script: [/entrypoint.sh]
  variables:
    BASEURL: https://devboxops.xyz
  environment:
    name: production
    url: "https://devboxops.xyz"
  artifacts:
    paths:
    - public
  only:
    - main

devel:
  only: [devel]
  artifacts:
    paths:
    - public
  variables:
    BASEURL: https://dev.devboxops.xyz
  environment:
    name: devel
    url: "https://dev.devboxops.xyz"
  script: [/entrypoint.sh]
  stage: deploy
