---
image:
  name: ghcr.io/oldtyt/hugo-docker
  entrypoint: [""]

variables:
  PUBLIC_URL: /

stages:
  - deploy

pages:
  stage: "deploy"
  script: [/entrypoint.sh]
  artifacts:
    paths:
    - public
  only:
    - main
